In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
# import pydot
%matplotlib inline

# 폰트 문제 해결하기
import platform

path = "c:/Windows/Fonts/malgun.ttf"
from matplotlib import font_manager, rc
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~')

In [2]:
data = pd.read_excel("2014Data.xlsx")
data.head()

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,Y1,Y2,Unnamed: 13,Unnamed: 14,만족도,명 수,백분율,Unnamed: 18
0,NaN,5,5,5,5,5,3,4,5,5,5,5,5,NaN,NaN,매우불만족,335.0,0.279120,NaN
1,NaN,4,4,4,4,4,3,3,5,4,4,5,4,NaN,NaN,불만족,2434.0,2.027995,120020.0
2,NaN,4,4,4,4,3,3,3,4,4,4,5,3,NaN,NaN,보통,17470.0,14.555907,NaN
3,NaN,4,4,3,2,3,8,8,2,2,4,2,3,NaN,NaN,만족,57639.0,48.024496,NaN
4,NaN,4,5,3,4,4,3,3,3,3,3,3,4,NaN,NaN,매우 만족,40039.0,33.360273,NaN

In [3]:
data = data.dropna(axis=1) # axis =1 열을 기준으로 삭제
data.head()

   X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  Y1  Y2
0   5   5   5   5   5   3   4   5   5    5   5   5
1   4   4   4   4   4   3   3   5   4    4   5   4
2   4   4   4   4   3   3   3   4   4    4   5   3
3   4   4   3   2   3   8   8   2   2    4   2   3
4   4   5   3   4   4   3   3   3   3    3   3   4

In [4]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms

In [8]:
from sklearn import preprocessing
import pandas as pd

X=pd.DataFrame(data, columns=["X1","X2","X3","X4","X5","X6","X7","X8","X9","X10"])
Y=pd.DataFrame(data, columns=["Y1"])

In [9]:
# 만족도와 재방문의사 회귀분석
linear_regression = sm.OLS(Y, X) # (종속변수, 독립변수)

# OLS 회귀모형 피팅
result_data = linear_regression.fit()

# 회귀분석 결과 요약
print(result_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y1   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.969
Method:                 Least Squares   F-statistic:                 3.761e+04
Date:                Sat, 09 Jun 2018   Prob (F-statistic):               0.00
Time:                        16:41:29   Log-Likelihood:                -13537.
No. Observations:               12024   AIC:                         2.709e+04
Df Residuals:                   12014   BIC:                         2.717e+04
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.1544      0.012     12.996      0.000       0.131       0.178
X2             0.0679      0.011      6.232      0.000       0.047       0.089
X3             0.1192      0.012      9.677      0.000       0.095       0.143
X4             0.2438      0.010     23.237      0.000       0.223       0.264
X5             0.0395      0.008      5.160      0.000       0.024       0.054
X6             0.0678      0.009      7.709      0.000       0.051       0.085
X7            -0.0015      0.007     -0.216      0.829      -0.015       0.012
X8             0.0813      0.009      9.224      0.000       0.064       0.099
X9             0.0065      0.010      0.643      0.520      -0.013       0.026
X10            0.2006      0.013     15.281      0.000       0.175       0.226
==============================================================================
Omnibus:                     1279.479   Durbin-Watson:                   1.838
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2385.883
Skew:                          -0.712   Prob(JB):                         0.00
Kurtosis:                       4.653   Cond. No.                         28.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [12]:
X=pd.DataFrame(data, columns=["X1","X2","X3","X4","X5","X6","X7","X8","X9","X10"])
Y=pd.DataFrame(data, columns=["Y2"])

In [13]:
# 만족도와 추천의사 회귀분석
linear_regression = sm.OLS(Y, X) # (종속변수, 독립변수)

# OLS 회귀모형 피팅
result_data = linear_regression.fit()

# 회귀분석 결과 요약
print(result_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y2   R-squared:                       0.980
Model:                            OLS   Adj. R-squared:                  0.980
Method:                 Least Squares   F-statistic:                 5.894e+04
Date:                Sat, 09 Jun 2018   Prob (F-statistic):               0.00
Time:                        16:41:56   Log-Likelihood:                -10977.
No. Observations:               12024   AIC:                         2.197e+04
Df Residuals:                   12014   BIC:                         2.205e+04
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.1529      0.010     15.926      0.000       0.134       0.172
X2             0.0964      0.009     10.945      0.000       0.079       0.114
X3             0.1354      0.010     13.599      0.000       0.116       0.155
X4             0.2073      0.008     24.449      0.000       0.191       0.224
X5             0.0112      0.006      1.808      0.071      -0.001       0.023
X6             0.0958      0.007     13.467      0.000       0.082       0.110
X7            -0.0340      0.006     -6.033      0.000      -0.045      -0.023
X8             0.0714      0.007     10.021      0.000       0.057       0.085
X9             0.0278      0.008      3.410      0.001       0.012       0.044
X10            0.2278      0.011     21.468      0.000       0.207       0.249
==============================================================================
Omnibus:                      530.186   Durbin-Watson:                   1.901
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              853.570
Skew:                          -0.386   Prob(JB):                    4.46e-186
Kurtosis:                       4.052   Cond. No.                         28.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.