## 1. 비즈니스 이해

### Background: 어떠한 문제가 존재하는지 상황에 대해 알려진 기사, 논문, 보고서 등을 인용하여 현상을 구체적으로 기술하시기 바랍니다.
- [국내 찾는 외국인 더 줄었다...1월 여행수지 적자 최대](http://www.ajunews.com/view/20180306083226894)
- 지난 1월 겨울방학을 맞아 해외여행을 다녀온 내국인이 늘었다. 반면 국내를 찾는 해외 관광객들의 발걸음은 뜸해지며 여행수지 적자가 역대 최대를 기록했다.
- 실제로 겨울방학을 맞아 해외 출국자수는 286만7000명으로 역대 최대를 기록했다. 1년 전에 비해 22.4% 증가했다. 이에 반해 전체 입국자수는 95만6000명으로 21.7% 감소했다. 특히 중국인 입국자수는 사드 보복 완화에도 불구하고 전년 대비 46.0% 감소한 30만5000명에 그쳤다.

### Business Objectives: 기업(혹은 본인)에게 이 현상이 어떠한 이유로 분석을 해야 하는지 추상적(함축적)으로 기술하시기 바랍니다.
- 국내여행을 온 외국인 관광객들의 선호도를 파악하고, 외국인 대상 국내 관광 산업 활성화 전략을 제공하여 여행수지 흑자에 도움이 되고자 함.

### Business Success Criteria: 비즈니스 관점에서 분석결과의 성공기준(정량적) 또는 유용한 결과에 대한 기준(정성적)을 설명하십시오.
- 여행사 입장에서 외국인 국내 관광 선호도 조사 결과를 통해, 외국인 관광객들을 연령, 여행 목적, 성별로 그룹화하여 맞춤 여행 코스와 예상 경비 정보를 제공, 작년과 비교하여 외국인 관광객 수를 늘린다.

### Analysis Goals: 비즈니스 목표에 대한 의사결정 지원을 위해 실시하는 분석의 목표를 기술합니다. 
- 2016년에 국내여행을 온 외국인 관광객들의 재방문 의사와 추천 여부, 총 지출 금액 양상 분석

## 2. 데이터의 이해
- 한국관광공사 외래관광객 실태자료 9개년 원자료 파일을 통해 데이터를 수집함.
- [2017 외래관광객 실태조사](https://kto.visitkorea.or.kr/kor/notice/data/statis/tstatus/forstatus/board/view.kto?id=429831&isNotice=false&instanceId=295&rnum=1)
    - 데이터: 2009년 ~ 2017년(9개년)
    - 외래관광객 대상 설문 : 매년 1회 실시(매년 약 12,000명)
- 데이터 전처리 : 한국 방문시 활동 내역(1, 2, 3순위)를 결합 / 집계, 3년 내 재방문 의사, 연령

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
# import pydot
%matplotlib inline

# 폰트 문제 해결하기
import platform

path = "c:/Windows/Fonts/malgun.ttf"
from matplotlib import font_manager, rc
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~')

In [2]:
data = pd.read_excel("dd.xlsx")
data.head()

   X1  X2  X3   X4  X5  X6  X7  X8  X9  X10  Y1  Y2
0   3   5   4  5.0   3   3   4   3   3    5   3   3
1   4   4   3  4.0   4   5   5   3   3    5   4   4
2   5   5   5  5.0   5   5   5   5   5    5   5   5
3   4   4   4  5.0   4   3   4   3   4    3   4   4
4   3   4   5  5.0   5   4   4   4   4    4   5   5

In [3]:
data = data.dropna(axis=1) # axis =1 열을 기준으로 삭제
data.head()

   X1  X2  X3  X5  X6  X7  X8  X9  X10  Y1  Y2
0   3   5   4   3   3   4   3   3    5   3   3
1   4   4   3   4   5   5   3   3    5   4   4
2   5   5   5   5   5   5   5   5    5   5   5
3   4   4   4   4   3   4   3   4    3   4   4
4   3   4   5   5   4   4   4   4    4   5   5

In [4]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms

In [19]:
from sklearn import preprocessing
import pandas as pd

X=pd.DataFrame(data, columns=["X1","X2","X3","X5","X6","X7","X8","X9","X10"])
Y=pd.DataFrame(data, columns=["Y1"])

In [22]:
# 만족도와 재방문의사 회귀분석
linear_regression = sm.OLS(Y, X) # (종속변수, 독립변수)

# OLS 회귀모형 피팅
result_data = linear_regression.fit()

# 회귀분석 결과 요약
print(result_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y1   R-squared:                       0.967
Model:                            OLS   Adj. R-squared:                  0.967
Method:                 Least Squares   F-statistic:                 3.914e+04
Date:                Sat, 09 Jun 2018   Prob (F-statistic):               0.00
Time:                        16:39:14   Log-Likelihood:                -14080.
No. Observations:               12003   AIC:                         2.818e+04
Df Residuals:                   11994   BIC:                         2.824e+04
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.0674      0.011      6.146      0.000       0.046       0.089
X2             0.1447      0.013     11.181      0.000       0.119       0.170
X3             0.1330      0.011     12.643      0.000       0.112       0.154
X5             0.0711      0.007     10.373      0.000       0.058       0.084
X6             0.1334      0.009     14.846      0.000       0.116       0.151
X7            -0.0056      0.007     -0.753      0.452      -0.020       0.009
X8             0.0904      0.010      9.435      0.000       0.072       0.109
X9             0.1182      0.012      9.835      0.000       0.095       0.142
X10            0.2176      0.014     15.749      0.000       0.191       0.245
==============================================================================
Omnibus:                     1425.085   Durbin-Watson:                   1.849
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2577.954
Skew:                          -0.791   Prob(JB):                         0.00
Kurtosis:                       4.629   Cond. No.                         29.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
from sklearn import preprocessing
import pandas as pd

X=pd.DataFrame(data, columns=["X1","X2","X3","X5","X6","X7","X8","X9","X10"])
Y=pd.DataFrame(data, columns=["Y2"])

In [24]:
# 만족도와 추천의사 회귀분석
linear_regression = sm.OLS(Y, X) # (종속변수, 독립변수)

# OLS 회귀모형 피팅
result_data = linear_regression.fit()

# 회귀분석 결과 요약
print(result_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y2   R-squared:                       0.979
Model:                            OLS   Adj. R-squared:                  0.979
Method:                 Least Squares   F-statistic:                 6.313e+04
Date:                Sat, 09 Jun 2018   Prob (F-statistic):               0.00
Time:                        16:39:41   Log-Likelihood:                -11415.
No. Observations:               12003   AIC:                         2.285e+04
Df Residuals:                   11994   BIC:                         2.291e+04
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.0724      0.009      8.238      0.000       0.055       0.090
X2             0.1877      0.010     18.106      0.000       0.167       0.208
X3             0.1355      0.008     16.087      0.000       0.119       0.152
X5             0.0203      0.005      3.705      0.000       0.010       0.031
X6             0.1145      0.007     15.910      0.000       0.100       0.129
X7            -0.0466      0.006     -7.886      0.000      -0.058      -0.035
X8             0.0853      0.008     11.106      0.000       0.070       0.100
X9             0.0943      0.010      9.800      0.000       0.075       0.113
X10            0.3244      0.011     29.309      0.000       0.303       0.346
==============================================================================
Omnibus:                      569.317   Durbin-Watson:                   1.830
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              853.783
Skew:                          -0.431   Prob(JB):                    4.01e-186
Kurtosis:                       3.982   Cond. No.                         29.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.