In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
# import pydot
%matplotlib inline

# 폰트 문제 해결하기
import platform

path = "c:/Windows/Fonts/malgun.ttf"
from matplotlib import font_manager, rc
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~')

In [2]:
data = pd.read_excel("2013Data.xlsx")
data.head()

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,Y1,Y2,Unnamed: 13,Unnamed: 14,만족도,명 수,백분율,Unnamed: 18
0,NaN,4,2,3,5,4,4,4,4,5,5,4,4,NaN,NaN,매우불만족,492.0,0.409932,NaN
1,NaN,4,3,3,3,4,4,4,3,3,2,5,5,NaN,NaN,불만족,2668.0,2.222963,120020.0
2,NaN,4,4,4,5,5,4,4,3,3,5,2,3,NaN,NaN,보통,21043.0,17.532911,NaN
3,NaN,5,5,5,5,5,5,5,5,5,5,4,4,NaN,NaN,만족,58060.0,48.375271,NaN
4,NaN,5,3,4,4,3,3,3,4,4,4,4,4,NaN,NaN,매우 만족,34734.0,28.940177,NaN

In [3]:
data = data.dropna(axis=1) # axis =1 열을 기준으로 삭제
data.head()

   X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  Y1  Y2
0   4   2   3   5   4   4   4   4   5    5   4   4
1   4   3   3   3   4   4   4   3   3    2   5   5
2   4   4   4   5   5   4   4   3   3    5   2   3
3   5   5   5   5   5   5   5   5   5    5   4   4
4   5   3   4   4   3   3   3   4   4    4   4   4

In [4]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms

In [5]:
from sklearn import preprocessing
import pandas as pd

X=pd.DataFrame(data, columns=["X1","X2","X3","X4","X5","X6","X7","X8","X9","X10"])
Y=pd.DataFrame(data, columns=["Y1"])

In [6]:
# 만족도와 재방문의사 회귀분석
linear_regression = sm.OLS(Y, X) # (종속변수, 독립변수)

# OLS 회귀모형 피팅
result_data = linear_regression.fit()

# 회귀분석 결과 요약
print(result_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y1   R-squared:                       0.967
Model:                            OLS   Adj. R-squared:                  0.967
Method:                 Least Squares   F-statistic:                 3.548e+04
Date:                Sat, 09 Jun 2018   Prob (F-statistic):               0.00
Time:                        16:58:52   Log-Likelihood:                -13709.
No. Observations:               12030   AIC:                         2.744e+04
Df Residuals:                   12020   BIC:                         2.751e+04
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.1080      0.011      9.440      0.000       0.086       0.130
X2             0.0306      0.010      3.048      0.002       0.011       0.050
X3             0.1590      0.012     13.609      0.000       0.136       0.182
X4             0.2441      0.010     23.595      0.000       0.224       0.264
X5             0.0626      0.006      9.662      0.000       0.050       0.075
X6             0.0862      0.008     10.741      0.000       0.070       0.102
X7            -0.0210      0.006     -3.465      0.001      -0.033      -0.009
X8             0.0798      0.009      9.301      0.000       0.063       0.097
X9             0.0176      0.010      1.689      0.091      -0.003       0.038
X10            0.2107      0.012     17.262      0.000       0.187       0.235
==============================================================================
Omnibus:                      706.271   Durbin-Watson:                   1.836
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1067.406
Skew:                          -0.502   Prob(JB):                    1.64e-232
Kurtosis:                       4.058   Cond. No.                         26.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

- 모델의 설명력(R-squared)
    - 즉, 결정계수가 0.967이라면 Y의 변동 중 96.7%이 회귀모형에 의해 설명되고 나머지 3.3%는 모형에 포함되지 않는 다른 요인들로 설명됨.
    - 단순 선형회귀에서는 상관계수r의 제곱과 정확히 일치함. r^2 = R^2
    - r=0.983 -> r^2=0.967 -> R^2 = 0.967 X와 Y의 상관관계가 높을수록 모형에 의해 데이터가 많이 설명될 수 있다.

In [7]:
X=pd.DataFrame(data, columns=["X1","X2","X3","X4","X5","X6","X7","X8","X9","X10"])
Y=pd.DataFrame(data, columns=["Y2"])

In [8]:
# 만족도와 추천의사 회귀분석
linear_regression = sm.OLS(Y, X) # (종속변수, 독립변수)

# OLS 회귀모형 피팅
result_data = linear_regression.fit()

# 회귀분석 결과 요약
print(result_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y2   R-squared:                       0.976
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                 4.817e+04
Date:                Sat, 09 Jun 2018   Prob (F-statistic):               0.00
Time:                        16:59:01   Log-Likelihood:                -11863.
No. Observations:               12030   AIC:                         2.375e+04
Df Residuals:                   12020   BIC:                         2.382e+04
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.1149      0.010     11.712      0.000       0.096       0.134
X2             0.0501      0.009      5.814      0.000       0.033       0.067
X3             0.1474      0.010     14.708      0.000       0.128       0.167
X4             0.2254      0.009     25.405      0.000       0.208       0.243
X5             0.0198      0.006      3.569      0.000       0.009       0.031
X6             0.0878      0.007     12.756      0.000       0.074       0.101
X7            -0.0511      0.005     -9.806      0.000      -0.061      -0.041
X8             0.0763      0.007     10.365      0.000       0.062       0.091
X9             0.0236      0.009      2.643      0.008       0.006       0.041
X10            0.2854      0.010     27.261      0.000       0.265       0.306
==============================================================================
Omnibus:                      336.247   Durbin-Watson:                   1.846
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              487.366
Skew:                          -0.298   Prob(JB):                    1.48e-106
Kurtosis:                       3.786   Cond. No.                         26.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

- 모델의 설명력(R-squared)
    - 즉, 결정계수가 0.976이라면 Y의 변동 중 97.6%이 회귀모형에 의해 설명되고 나머지 2.4%는 모형에 포함되지 않는 다른 요인들로 설명됨.
    - 단순 선형회귀에서는 상관계수r의 제곱과 정확히 일치함. r^2 = R^2
    - r=0.988 -> r^2=0.976 -> R^2 = 0.976 X와 Y의 상관관계가 높을수록 모형에 의해 데이터가 많이 설명될 수 있다.